// 解析接口列表
export const parsingServices = [
    // ================= 通用解析接口 =================
    { name: "普通接口", url: "https://jx.playerjy.com/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "高速接口", url: "http://jiexi44.qmbo.cn/jiexi/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "超清接口", url: "https://z1.m1907.top/?jx=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "常用接口", url: "https://yemu.xyz/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "海外接口", url: "https://jx.77flv.cc/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "VIP解析1", url: "https://api.52kdy.cn/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "蓝光接口", url: "https://jx.iztyy.com/svip/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "聚合解析", url: "https://jx.m3u8.tv/jiexi/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "无广告接口", url: "https://jx.ckplayer.vip/jx/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "万能解析", url: "https://jx.playerjtr.com/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "备用解析1", url: "https://jx.bozrc.com:4433/player/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "备用解析2", url: "https://jx.mmkv.cn/tv.php?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "4K专用", url: "https://jx.4kyy.top/?url=", type: "通用解析", status: "unknown", latency: 0 },
    { name: "移动优化", url: "https://m3u8.cqfenfa.com/jx/?url=", type: "通用解析", status: "unknown", latency: 0 },
  
    // ================= 抖音/TikTok专用 =================
    { name: "抖音元数据解析", url: "https://api.pearktrue.cn/api/video/douyin/?url=", type: "抖音/TikTok", status: "unknown", latency: 0 },
    { name: "Ceacer抖音去水印", url: "https://douyin.ceacer.cn/?url=", type: "抖音/TikTok", status: "unknown", latency: 0 },
    { name: "Vnil抖音批量", url: "https://api.vnil.cn/api/customparse/getList?appkey=YOUR_KEY&url=", type: "抖音/TikTok", status: "unknown", latency: 0 },
  
    // ================= 多平台万能解析 =================
    { name: "Pear万能解析", url: "https://api.pearktrue.cn/api/video/api.php?url=", type: "多平台万能", status: "unknown", latency: 0 },
    { name: "Vnil无水印解析", url: "https://api.vnil.cn/api/parse?url=", type: "多平台万能", status: "unknown", latency: 0 },
    { name: "iCodeQ聚合解析", url: "https://api.icodeq.com/api/wechat_video_public?wxv_", type: "多平台万能", status: "unknown", latency: 0 },
  
    // ================= B站专用 =================
    { name: "B站解析", url: "https://jx.xyflv.cc/?url=", type: "B站专用", status: "unknown", latency: 0 },
    { name: "B站直链提取", url: "https://video-direct-link.vercel.app/bili.mp4?aid={aid}&bvid={bvid}&cid={cid}", type: "B站专用", status: "unknown", latency: 0 },
    { name: "B站半自动解析", url: "https://icodeq-bpi.vercel.app/api/parwix?url=", type: "B站专用", status: "unknown", latency: 0 },
  
    // ================= 平台专用接口 =================
    { name: "芒果专用", url: "https://jx.yangtu.top/?url=", type: "平台专用", status: "unknown", latency: 0 },
    { name: "腾讯解析", url: "https://jx.ivito.cn/?url=", type: "平台专用", status: "unknown", latency: 0 },
    { name: "爱奇艺专线", url: "https://jx.aidouer.net/?url=", type: "平台专用", status: "unknown", latency: 0 },
    { name: "微信视频直链", url: "https://api.icodeq.com/api/wechat_video_public?wxv_", type: "平台专用", status: "unknown", latency: 0 },
    { name: "微博307协议", url: "https://api.icodeq.com/api/weibo_307_video?uid={uid}&cursor={cursor}&hd={hd}", type: "平台专用", status: "unknown", latency: 0 },
    { name: "网易MV直链", url: "https://163.icodeq.com/?vid=", type: "平台专用", status: "unknown", latency: 0 },
    { name: "网易MV逆向", url: "https://api.icodeq.com/api/get_163_mv_vercel?vid=", type: "平台专用", status: "unknown", latency: 0 },
    { name: "YouTube专用", url: "https://yt.icodeq.com/dl?url=", type: "平台专用", status: "unknown", latency: 0 },
  
    // ================= 海外加速 =================
    { name: "海外加速", url: "https://jx.jsonplayer.com/player/?url=", type: "海外加速", status: "unknown", latency: 0 },
    { name: "TikTok国际版", url: "https://api.intl.icodeq.com/tiktok?url=", type: "海外加速", status: "unknown", latency: 0 },
    { name: "Twitter视频解析", url: "https://tw.icodeq.com/video?tweet_url=", type: "海外加速", status: "unknown", latency: 0 },
  
    // ================= 备用接口 =================
    { name: "解析备用01", url: "https://jx.playerjy.cn/jx2/?url=", type: "备用接口", status: "unknown", latency: 0 },
    { name: "解析备用02", url: "https://parse.video/api/?url=", type: "备用接口", status: "unknown", latency: 0 },
    { name: "解析备用03", url: "https://vip.jxplayer.top/?url=", type: "备用接口", status: "unknown", latency: 0 },
    { name: "解析备用04", url: "http://45.136.28.100:88/jiexi/?url=", type: "备用接口", status: "unknown", latency: 0 },
    { name: "解析备用05", url: "https://jx.ergan.top/?url=", type: "备用接口", status: "unknown", latency: 0 },
  
    // ================= 特殊场景接口 =================
    { name: "直播流解析", url: "https://live.icodeq.com/m3u8?url=", type: "特殊场景", status: "unknown", latency: 0 },
    { name: "VR视频专用", url: "https://vr.parse.video/?equirect=", type: "特殊场景", status: "unknown", latency: 0 },
    { name: "8K超高清", url: "https://8k.video/api/parse?token=YOUR_TOKEN&url=", type: "特殊场景", status: "unknown", latency: 0 }
  ];
  
  // 多语言文本
  export const translations = {
    zh: {
      appTitle: "视频解析助手",
      appSubtitle: "一键解析各大平台VIP视频",
      darkText: "暗色模式",
      lightText: "亮色模式",
      langText: "English",
      announcementText: "公告",
      urlTitle: "当前页面链接",
      fetchingUrl: "正在获取当前页面URL...",
      copyText: "复制",
      serviceTitle: "选择解析接口",
      randomText: "随机接口",
      randomDesc: "每次随机选择可用接口",
      parseText: "开始解析",
      footerText: "© 2025 视频解析助手 | 仅供学习交流使用",
      notificationText: "已复制到剪贴板",
      announcementTitle: "重要公告",
      onlineText: "在线",
      offlineText: "离线",
      allText: "全部",
      refreshText: "刷新接口状态",
      customTitle: "添加自定义接口",
      nameLabel: "接口名称",
      urlLabel: "接口URL",
      typeLabel: "接口类型",
      testText: "测试接口",
      addText: "添加接口",
      namePlaceholder: "接口名称",
      urlPlaceholder: "https://example.com/?url=",
      noServicesText: "没有匹配的接口",
      generalType: "通用解析",
      douyinType: "抖音/TikTok",
      multiType: "多平台万能",
      bilibiliType: "B站专用",
      platformType: "平台专用",
      overseasType: "海外加速",
      backupType: "备用接口",
      specialType: "特殊场景",
      
      announcementGreeting: "尊敬的插件用户：",
      announcementUpdate: "我们很高兴地宣布视频解析助手插件 v3.0 版本正式发布！本次更新带来了多项改进和新功能：",
      update1: "新增接口状态实时检测功能",
      update2: "支持自定义接口添加与管理",
      update3: "按类型分类展示接口",
      update4: "优化了接口选择体验",
      update5: "全新的现代化UI设计",
      tipsTitle: "使用提示",
      tip1: "1. 遇到解析失败时，请尝试切换其他接口",
      tip2: "2. 随机接口模式会自动选择当前可用性最好的解析服务",
      tip3: "3. 推荐使用暗色模式在夜间使用本插件",
      announcementFooter: "我们致力于为您提供最好的视频解析体验。如果您有任何问题或建议，请访问我们的",
      githubText: "GitHub页面",
      announcementFooter2: "提交反馈。",
      thanksText: "感谢您使用视频解析助手！",
      signature: "开发团队敬上"
    },
    en: {
      appTitle: "Video Parser Pro",
      appSubtitle: "VIP Video Parsing with One Click",
      darkText: "Dark Mode",
      lightText: "Light Mode",
      langText: "中文",
      announcementText: "Announcement",
      urlTitle: "Current Page URL",
      fetchingUrl: "Fetching current URL...",
      copyText: "Copy",
      serviceTitle: "Select Parsing Service",
      randomText: "Random Service",
      randomDesc: "Select a random service each time",
      parseText: "Parse Now",
      footerText: "© 2025 Video Parser Pro | For Educational Use Only",
      notificationText: "Copied to clipboard",
      announcementTitle: "Important Announcement",
      onlineText: "Online",
      offlineText: "Offline",
      allText: "All",
      refreshText: "Refresh Status",
      customTitle: "Add Custom Service",
      nameLabel: "Service Name",
      urlLabel: "Service URL",
      typeLabel: "Service Type",
      testText: "Test Service",
      addText: "Add Service",
      namePlaceholder: "Service name",
      urlPlaceholder: "https://example.com/?url=",
      noServicesText: "No matching services",
      generalType: "General",
      douyinType: "Douyin/TikTok",
      multiType: "Multi-platform",
      bilibiliType: "Bilibili",
      platformType: "Platform Specific",
      overseasType: "Overseas",
      backupType: "Backup",
      specialType: "Special Scenarios",
      
      announcementGreeting: "Dear plugin users:",
      announcementUpdate: "We are pleased to announce the official release of Video Parser Pro v3.0! This update brings multiple improvements and new features:",
      update1: "Added real-time service status detection",
      update2: "Support for custom service management",
      update3: "Services categorized by type",
      update4: "Improved service selection experience",
      update5: "Completely redesigned modern UI",
      tipsTitle: "Usage Tips",
      tip1: "1. If parsing fails, try switching to another service",
      tip2: "2. Random service mode selects the best available service",
      tip3: "3. Dark mode is recommended for night use",
      announcementFooter: "We are committed to providing the best video parsing experience. If you have any questions or suggestions, please visit our",
      githubText: "GitHub page",
      announcementFooter2: "to submit feedback.",
      thanksText: "Thank you for using Video Parser Pro!",
      signature: "Development Team"
    }
  };